### ISSUE TITLE
linux用户不能用在说明里标一下，我还试着运行了下，难受。

### ISSUE THREAD

**Issue by xtccc** [MR5356/System-assistant#2]
你用的这个Sub_Thread.py 中subprocess.STARTUPINFO() 我查了下不支持linux 而且你直接调用了.exe，linux应该是无缘了。

顺便说一句，写的挺好，小白没太看懂

**Comment by MR5356** [comment]
不好意思啊，因为我一直用Windows版本测试，忽略了Linux上的不兼容，如果在Linux上使用的话将自动更新的thread注释掉，稍微修改一下下载器代码就可以了。之后的版本我会加上判断的代码的

具体操作，
1、将function.py中的3行：import subprocess、121行：self.update_thread() 注释掉
2、将Sub_Thread.py中的Download_Thread中调用的.exe更换为aria2对应的Linux版本(之后我会添加上的)，startupinfo是为了隐藏窗口，可以去掉这几行的

当然，我也尽快修复一下这个问题
